"""
Modern AI Image Detector
=========================

Detects images generated by modern AI generators:
- DALL-E 3
- Midjourney v6
- Stable Diffusion 3
- Flux

Uses Hugging Face transformers with pre-trained AI detection models.
"""

import os
from PIL import Image
from typing import Dict, Optional
import warnings

# Suppress warnings for cleaner output
warnings.filterwarnings("ignore")


class ModernAIDetector:
    """
    Detector for modern AI-generated images using Hugging Face models.

    Works on DALL-E 3, Midjourney v6, Stable Diffusion 3, and other
    state-of-the-art generators that traditional detectors miss.
    """

    MODEL_NAME = "umm-maybe/AI-image-detector"  # Pre-trained on modern AI
    MODEL_VERSION = "1.0.0"

    def __init__(self):
        """Initialize the modern AI detector."""
        self._pipeline = None
        self._loaded = False

    def _load_model(self):
        """Lazy load the model (downloads on first use)."""
        if self._loaded:
            return

        try:
            from transformers import pipeline

            print("📥 Loading modern AI detector (first run may take a minute)...")
            self._pipeline = pipeline(
                "image-classification",
                model=self.MODEL_NAME,
                device=-1,  # CPU (-1) or GPU (0)
            )
            self._loaded = True
            print(f"✅ Loaded: {self.MODEL_NAME}")

        except ImportError:
            raise RuntimeError(
                "transformers library not installed. Run:\n" "pip install transformers"
            )
        except Exception as e:
            raise RuntimeError(f"Failed to load model: {e}")

    def predict(self, image_path: str) -> Dict:
        """
        Predict if an image is AI-generated.

        Args:
            image_path: Path to the image file

        Returns:
            dict with:
                - synthetic_probability: float (0-1)
                - synthetic_likelihood: str
                - confidence_band: str
                - model: str
                - details: dict (raw model output)
        """
        self._load_model()

        # Load and classify image
        image = Image.open(image_path).convert("RGB")
        results = self._pipeline(image)

        # Parse results - model returns labels like "artificial", "human"
        ai_prob = 0.0
        for result in results:
            label = result["label"].lower()
            score = result["score"]

            if "artificial" in label or "ai" in label or "fake" in label:
                ai_prob = score
                break
            elif "human" in label or "real" in label:
                ai_prob = 1.0 - score
                break

        # Build response
        return {
            "synthetic_probability": ai_prob,
            "synthetic_likelihood": self._get_likelihood(ai_prob),
            "confidence_band": self._get_confidence(ai_prob),
            "model": f"Modern AI Detector ({self.MODEL_NAME})",
            "model_version": self.MODEL_VERSION,
            "details": results,
            "best_for": "DALL-E 3, Midjourney v6, Stable Diffusion 3",
        }

    def _get_likelihood(self, prob: float) -> str:
        """Convert probability to language label."""
        if prob < 0.2:
            return "LOW synthetic likelihood"
        elif prob < 0.4:
            return "MODERATE-LOW synthetic likelihood"
        elif prob < 0.6:
            return "INCONCLUSIVE"
        elif prob < 0.8:
            return "MODERATE-HIGH synthetic likelihood"
        else:
            return "HIGH synthetic likelihood"

    def _get_confidence(self, prob: float) -> str:
        """Get confidence band."""
        if 0.3 <= prob <= 0.7:
            return "MEDIUM confidence (inconclusive zone)"
        else:
            return "HIGH confidence"


def check_metadata_watermarks(image_path: str) -> Dict:
    """
    Check image metadata for C2PA watermarks and AI provenance.

    DALL-E 3 and other platforms embed invisible watermarks
    in image metadata.

    Args:
        image_path: Path to image file

    Returns:
        dict with watermark detection results
    """
    try:
        from PIL import Image
        from PIL.ExifTags import TAGS

        img = Image.open(image_path)

        # Check EXIF data
        exif_data = {}
        if hasattr(img, "_getexif") and img._getexif():
            for tag_id, value in img._getexif().items():
                tag = TAGS.get(tag_id, tag_id)
                exif_data[tag] = value

        # Check for known AI watermark indicators
        ai_indicators = []

        # Check software field
        software = exif_data.get("Software", "")
        if any(
            x in software.lower()
            for x in ["dall-e", "midjourney", "stable diffusion", "openai"]
        ):
            ai_indicators.append(f"Software: {software}")

        # Check image description
        desc = exif_data.get("ImageDescription", "")
        if any(
            x in desc.lower() for x in ["artificial", "generated", "ai", "synthetic"]
        ):
            ai_indicators.append(f"Description: {desc}")

        # Check for C2PA manifest (Content Credentials)
        # C2PA uses XMP metadata; simple check here
        try:
            from PIL import PngImagePlugin

            if hasattr(img, "info"):
                for key, value in img.info.items():
                    if (
                        "c2pa" in str(key).lower()
                        or "contentcredentials" in str(key).lower()
                    ):
                        ai_indicators.append(f"C2PA: {key}")
        except:
            pass

        has_watermark = len(ai_indicators) > 0

        return {
            "has_ai_watermark": has_watermark,
            "indicators": ai_indicators,
            "exif_software": software,
            "message": (
                "AI watermark detected!"
                if has_watermark
                else "No obvious watermarks found"
            ),
        }

    except Exception as e:
        return {
            "has_ai_watermark": False,
            "indicators": [],
            "error": str(e),
            "message": "Could not check metadata",
        }


# Convenience function
def detect_modern_ai(image_path: str) -> Dict:
    """
    Full detection pipeline for modern AI images.

    Combines metadata checking + visual analysis.

    Args:
        image_path: Path to image

    Returns:
        Combined detection results
    """
    results = {
        "image": image_path,
        "metadata": check_metadata_watermarks(image_path),
        "visual_analysis": None,
    }

    try:
        detector = ModernAIDetector()
        results["visual_analysis"] = detector.predict(image_path)
    except Exception as e:
        results["visual_analysis"] = {"error": str(e)}

    # Combined verdict
    metadata_positive = results["metadata"].get("has_ai_watermark", False)
    visual_prob = results.get("visual_analysis", {}).get("synthetic_probability", 0)

    if metadata_positive:
        verdict = "LIKELY AI-GENERATED (watermark found)"
        probability = max(0.9, visual_prob)  # High confidence if watermark exists
    elif visual_prob > 0.7:
        verdict = "LIKELY AI-GENERATED"
        probability = visual_prob
    elif visual_prob > 0.4:
        verdict = "POSSIBLY AI-GENERATED"
        probability = visual_prob
    else:
        verdict = "LIKELY REAL"
        probability = visual_prob

    results["verdict"] = verdict
    results["combined_probability"] = probability

    return results


if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1:
        result = detect_modern_ai(sys.argv[1])
        print(f"\nVerdict: {result['verdict']}")
        print(f"Probability: {result['combined_probability']:.1%}")
